### ISSUE TITLE
Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler

### ISSUE THREAD

**Issue by qnoblet-luna** [snapcall/snapcall_sdk_ios#1]
**What did you do?**
I just updated to the version of Xcode Version 11.4 I opened a project I was working on and Xcode threw the error Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler. for Snapcall_Framework.
 I’m using CocoaPods as my package manager.

**What did you expect to happen?**
Frameworks compiled with Swift 5.2 compiler

**What happened instead?**
I am getting an error Module compiled with Swift 5.1.3 cannot be imported by the Swift 5.2 compiler. for Snapcall_Framework.

**Environment**
Snapcall_Framework (5.5.4)
Xcode version: 11.4 (11B52)
Platform(s) running: iOS

**Possible solution**
Module compiled with Swift 5.2
or
According to stackoverflow question BUILD_LIBRARY_FOR_DISTRIBUTION = YES; has to be set in Snapcall_Framework's project.pbxproj file.

**Comment by pnoyelle** [comment]
Hi , effectively apple released a new version , we will be up to date as soon as possible. I will release a new build and take you  informed. 
Thanks for your report.

**Comment by pnoyelle** [comment]
As temporary solution I compiled a version with latest xcode, find it in the branch called pre-release. I will make the official release in the next 24h.

**Comment by pnoyelle** [comment]
release 5.5.5 is out
