### ISSUE TITLE
Can't build using Carthage

### ISSUE THREAD

**Issue by clapslock** [snapcall/snapcall_sdk_ios#3]
Carthage is unable to build version `5.5.5-bitcode`.  Every try ends with this output: 

First 

`Incompatible Swift version - framework was built with 5.2 (swiftlang-1103.0.32.1 clang-1103.0.32.29) and the local version is 5.2.4 (swiftlang-1103.0.32.9 clang-1103.0.32.53).`

and then 
`Dependency "snapcall_sdk_ios" has no shared framework schemes for any of the platforms: iOS`

Xcode 11.7

**Comment by pnoyelle** [comment]
Hi @clapslock.
Please use latest snapcall version [5.6.6](https://github.com/snapcall/snapcall_sdk_ios/releases/tag/5.6.6) build for latest xcode.
bitcode is now supported in all Snapcall build, only the dependency for [webrtc](https://github.com/pnoyelle/iOSWebRTCFramework/releases/tag/76.0.0.bitcode) need change to use bitcode.

If upgrading  is not an option reach me again.

**Comment by clapslock** [comment]
Updating Xcode is not an option at the moment. 
I've updated the version to 5.6.6 as requested, but I'm still unable to build it using Carthage. I still get `Dependency "snapcall_sdk_ios" has no shared framework schemes for any of the platforms: iOS` when running `carthage update snapcall_sdk_ios --platform iOS --cache-builds`

Should `5.6.6` work with Xcod 11.7? 
I can share some of my configuration if needed

**Comment by pnoyelle** [comment]
It's only the xcode version  that cause the issue. 
Xcode 11.7 is still available for download on apple, I build the library on it and release a compatible build.

**Comment by clapslock** [comment]
Could you ping me when the compatible version is live?

**Comment by pnoyelle** [comment]
@clapslock  `github "snapcall/snapcall_sdk_ios" == 5.6.6-xcode11.7` should work.

**Comment by clapslock** [comment]
Thank you! 
We were using 5.5.5 till now. Any updates required when migrating to 5.6.6 ?

**Comment by pnoyelle** [comment]
It should be fully compatible , we essentially improved the code and made some fix.

**Comment by clapslock** [comment]
Follow up: Does this build support bitcode? If not, we will not be able to submit the app to the AppStore
