### ISSUE TITLE
Support for SPM

### ISSUE THREAD

**Issue by matkuznik** [snapcall/snapcall_sdk_ios#4]
Do you plan to add support for Swift Package Manager?

**Comment by pnoyelle** [comment]
Hi @matkuznik, yes it is something we can add on the next release.
There isn't new release planed , but if it's something you need, i can do one for that.

**Comment by matkuznik** [comment]
Currently, we are planning to migrate our dependencies to SPM so it is not urgent for now. If you add a support for the SPM to the end of the January it will be ok for us. 

Thanks in advance.

**Comment by matkuznik** [comment]
Hi @pnoyelle. Can you give me an update on this topic?

**Comment by pnoyelle** [comment]
Hi @matkuznik sorry for the delay, I get back on it .

**Comment by pnoyelle** [comment]
@matkuznik I'm validating the builld, it will be released before the end of the week.

**Comment by matkuznik** [comment]
Wow. Great to hear. Thanks a lot :)

**Comment by pnoyelle** [comment]
Hi @matkuznik , the build is online, the only change should be our unique dependency. 
It seems that you will have to add the dependency yourself to compile, i try to find reason. 
https://github.com/pnoyelle/WebRTC_IOS

**Comment by matkuznik** [comment]
Thanks. I have an additional question.

In the `Package.swift` I can see:
```
     platforms: [
        .iOS(.v13)
    ],
```
Does it mean that you do not support iOS 12 anymore?

**Comment by pnoyelle** [comment]
Sorry did not pay enought attention to that, we should support all version from 10. 
this prevent compilation ? if so i will  update it.

**Comment by matkuznik** [comment]
Awesome. I will try it next week.

**Comment by matkuznik** [comment]
Hi.
It does not prevent compilation. 
Unfortunately, I have encountered an error when trying to send the build to TestFlight:

```
1 package(s) were not uploaded because they had problems:
	/var/folders/fv/mfngcbh16hl87rsf72lq72ph0000gn/T/7EDE9D0E-6F62-4506-8725-BA8C047125DB/543921619.itmsp - Error Messages:
		ERROR ITMS-90680: "Invalid directory. The bundle Payload/MyApp.app/PlugIns/Snapcall_Framework.framework is not contained in a correctly named directory. It should be under "Frameworks"."
		ERROR ITMS-90680: "Invalid directory. The bundle Payload/MyApp.app/PlugIns/WebRTC.framework is not contained in a correctly named directory. It should be under "Frameworks"."
		ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'snapcall.Snapcall-Framework' under the iOS application 'MyApp.app'."
		ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.webrtc.WebRTC' under the iOS application 'MyApp.app'."
		
2021-04-09 16:14:24.482 altool[86527:4216588] *** Error: Error uploading '/Users/ci/Library/Caches/XCSBuilder/Integration-f91f618376321aa2a4069292b90572cc/ExportedProduct/MyApp.ipa'.
2021-04-09 16:14:24.483 altool[86527:4216588] *** Error: code -18000 (ERROR ITMS-90680: "Invalid directory. The bundle Payload/MyApp.app/PlugIns/Snapcall_Framework.framework is not contained in a correctly named directory. It should be under "Frameworks".")
2021-04-09 16:14:24.483 altool[86527:4216588] *** Error: code -18000 (ERROR ITMS-90680: "Invalid directory. The bundle Payload/MyApp.app/PlugIns/WebRTC.framework is not contained in a correctly named directory. It should be under "Frameworks".")
2021-04-09 16:14:24.483 altool[86527:4216588] *** Error: code -18000 (ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'snapcall.Snapcall-Framework' under the iOS application 'MyApp.app'.")
2021-04-09 16:14:24.483 altool[86527:4216588] *** Error: code -18000 (ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'org.webrtc.WebRTC' under the iOS application 'MyApp.app'.")
```

**Comment by pnoyelle** [comment]
Hi.
Seems more an error with xcode , i ll check monday.

**Comment by matkuznik** [comment]
Yes, I think that too. AFAIK should be fixed with the Xcode 12.5 🤞🏻

**Comment by matkuznik** [comment]
Hi. Unfortunately, Xcode 12.5 is unstable for us. The app itself works well, but UITests are very flaky, so I can not say for 100% whether it works as our pipeline fails. But I could send the app to the AppStoreConnect from my mac, so it looks ok:).

**Comment by pnoyelle** [comment]
@matkuznik We switched to xcframework in latest build to add arm64 simulator aarch, maybe it helped on your issue.

**Comment by matkuznik** [comment]
Hi, sorry for the late answer; I was off for a few days. Yesterday, Apple released Xcode 12.5.1, which addresses our issue. We are now testing it. Hopefully, we will be able to move to the SPM soon :)

**Comment by matkuznik** [comment]
Hi @pnoyelle. We were able to go live with Snapcall SDK integrated via SPM.
Thank you for your help :).

**Comment by pnoyelle** [comment]
Hi, Nice @matkuznik, thanks for the feedback.
